set -g mouse on

set -g mode-keys vi

set -as terminal-overrides ",xterm-256color:RGB"

set -g set-clipboard on

set -g history-limit 100000

setw -g aggressive-resize on

set -g set-titles on
set -g set-titles-string "(tmux) #h: #W"

set -g base-index 1
setw -g pane-base-index 1

setw -g renumber-windows on

set -g escape-time 200

bind -n "M-0" select-window -t ":^"
bind -n "M-1" select-window -t ":1"
bind -n "M-2" select-window -t ":2"
bind -n "M-3" select-window -t ":3"
bind -n "M-4" select-window -t ":4"
bind -n "M-5" select-window -t ":5"
bind -n "M-6" select-window -t ":6"
bind -n "M-7" select-window -t ":7"
bind -n "M-8" select-window -t ":8"
# Browsers also select last tab with M-9.
bind -n "M-9" select-window -t ":$"
# Match iTerm2.
bind -n "M-{" previous-window
bind -n "M-}" next-window

bind -n "M-S-{" previous-window
bind -n "M-S-}" next-window

# Toggle terminal mouse support.
bind m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# Toggle status bar. Useful for fullscreen focus.
bind t set-option status

bind r {
    copy-mode
    command-prompt -i -p "(search up)" \
        "send-keys -X search-backward-incremental '%%%'"
}

bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R

bind-key r source-file ~/.tmux.conf \; display "Config reloaded!"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -s extended-keys on

run-shell "$(dirname $(realpath ~/.tmux.conf))/extrakto/extrakto.tmux"
